# Generated by Django 3.0.3 on 2020-03-16 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200303_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='utils_password',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
