# Generated by Django 3.0.3 on 2020-02-29 21:40

from django.db import migrations, models
import gallery.models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_gallery_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image_gallery',
            field=models.ImageField(blank=True, null=True, upload_to=gallery.models.get_galleries_image),
        ),
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='image',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=gallery.models.get_users_gallery),
        ),
    ]
