# Generated by Django 3.0.3 on 2020-03-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0010_auto_20200303_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
