# Generated by Django 3.0.3 on 2020-03-03 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0011_postimage_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='name',
        ),
    ]
