# Generated by Django 3.0.3 on 2020-03-10 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0014_auto_20200310_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='is_check',
        ),
    ]
