# Generated by Django 3.0.3 on 2020-03-10 19:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0015_remove_image_is_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
