# Generated by Django 3.0.3 on 2020-03-10 19:21

from django.db import migrations, models
import uuid

from gallery.models import Image


def gen_uuid(apps, schema_editor):
    for image in Image.objects.all():
        image.unique_id = uuid.uuid4()
        image.save(update_fields=['unique_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0016_image_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='unique_id',
            field=models.UUIDField(
                default=uuid.uuid4, unique=True, editable=False),
            preserve_default=True,
        ),

        migrations.AlterField(
            model_name='image',
            name='unique_id',
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
