# Generated by Django 3.0.3 on 2020-03-10 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0017_auto_20200310_2121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='unique_id',
            new_name='unique_i',
        ),
    ]
