# Generated by Django 3.0.3 on 2020-03-10 19:33

from django.db import migrations, models
import uuid

from gallery.models import Image


def create_uuid(apps, schema_editor):
    images = Image.objects.all()
    for image in images:
        image.unique_id = uuid.uuid4()
        image.save()


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0019_remove_image_unique_i'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='unique_id',
            field=models.UUIDField(
                blank=True, null=True, primary_key=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.RunPython(create_uuid),
        migrations.AlterField(
            model_name='image',
            name='unique_id',
            field=models.UUIDField(
                default=uuid.uuid4, unique=True,  blank=True, null=True, primary_key=True)
        )
    ]
