# Generated by Django 3.0.3 on 2020-03-10 19:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0022_auto_20200310_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='unique_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
