# Generated by Django 3.0.3 on 2020-03-15 10:37

from django.db import migrations, models
import django.db.models.deletion
import gallery.models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0023_auto_20200310_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageS3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(blank=True, max_length=100, null=True)),
                ('images', models.ImageField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage, upload_to=gallery.models.get_users_gallery)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images_s3', to='gallery.Gallery')),
            ],
        ),
    ]
