# Generated by Django 3.0.3 on 2020-03-16 08:22

from django.db import migrations, models
import gal_pro.storage_backends
import gallery.models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0024_images3'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZipMaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_f', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='postimage',
            name='post',
        ),
        migrations.AlterField(
            model_name='images3',
            name='images',
            field=models.ImageField(blank=True, null=True, storage=gal_pro.storage_backends.MediaStorage(), upload_to=gallery.models.get_users_gallery),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
