# Generated by Django 3.0.3 on 2020-03-16 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0025_auto_20200316_1022'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ZipMaker',
        ),
    ]
