# Generated by Django 3.0.3 on 2020-03-08 19:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FileUploader',
            new_name='FileUpload',
        ),
    ]
