# Generated by Django 3.0.3 on 2020-03-15 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_auto_20200308_1225'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileUpload',
        ),
    ]
